# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Main Workflow

on: push

jobs:
  build-backend:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
        working-directory: ./backend
      - name: Build Backend
        run: npm run build --if-present
        working-directory: ./backend
      - name: Test Backend
        run: npm test
        working-directory: ./backend
      - name: Install typescript
        run: yarn global add typescript
      - name: Create Typedoc Documentation Frontend
        working-directory: ./frontend
        run: typedoc --tsconfig .\typedoc.json --out ../docs/frontend
      - name: Create Typedoc Documentation Backend 
        working-directory: ./backend
        run: typedoc --tsconfig .\typedoc.json --out ../docs/backend
      - name: Upload Docs to Github Repo
        uses: actions/upload-artifact@v2.2.3
        with:
          name: /docs 
